//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FreightFinder.Core.Model;

namespace FreightFinder.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FreightFinder : DbContext
    {
        public FreightFinder()
            : base("name=FreightFinder")
        {
            Configuration.ProxyCreationEnabled = false;
            Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<CreditTransfer> CreditTransfers { get; set; }
        public virtual DbSet<Destination> Destinations { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Employment> Employments { get; set; }
        public virtual DbSet<FreightAd> FreightAds { get; set; }
        public virtual DbSet<FreightType> FreightTypes { get; set; }
        public virtual DbSet<OffersToFreight> OffersToFreights { get; set; }
        public virtual DbSet<OffersToVehicle> OffersToVehicles { get; set; }
        public virtual DbSet<ShipperCompany> ShipperCompanies { get; set; }
        public virtual DbSet<ShipperCompanyUser> ShipperCompanyUsers { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransportationCompany> TransportationCompanies { get; set; }
        public virtual DbSet<TransportationCompanyUser> TransportationCompanyUsers { get; set; }
        public virtual DbSet<UserAuthorisationType> UserAuthorisationTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<VehicleAd> VehicleAds { get; set; }
        public virtual DbSet<VehicleLocation> VehicleLocations { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
    }
}
