//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightFinder.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditTransfer
    {
        public int TransferId { get; set; }
        public int CompanyId { get; set; }
        public int VehicleId { get; set; }
        public decimal Amount { get; set; }
        public decimal CompanyBalance { get; set; }
        public System.DateTime TransferDate { get; set; }
    
        public virtual TransportationCompany TransportationCompany { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
