//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightFinder.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.Employments = new HashSet<Employment>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int DriverId { get; set; }
        public int DrivingLicenseNo { get; set; }
        public int UserId { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string BloodType { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Employment> Employments { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
