//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightFinder.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment
    {
        public long EmploymentId { get; set; }
        public int CompanyId { get; set; }
        public int VehicleId { get; set; }
        public int DriverId { get; set; }
        public System.DateTime EmploymentStartDate { get; set; }
        public Nullable<System.DateTime> EmploymentEndDate { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual TransportationCompany TransportationCompany { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
