//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightFinder.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreightType
    {
        public FreightType()
        {
            this.FreightAds = new HashSet<FreightAd>();
        }
    
        public int FreightTypeId { get; set; }
        public string FreightTypeName { get; set; }
    
        public virtual ICollection<FreightAd> FreightAds { get; set; }
    }
}
