//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightFinder.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreightAd
    {
        public FreightAd()
        {
            this.OffersToFreights = new HashSet<OffersToFreight>();
        }
    
        public long FreightAdId { get; set; }
        public int BusinessId { get; set; }
        public int VehicleTypeId { get; set; }
        public int FreightTypeId { get; set; }
        public int Weight { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public System.DateTime AdDate { get; set; }
        public System.DateTime LoadingDate { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public bool KDV { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public string Description { get; set; }
        public bool IsDelivered { get; set; }
    
        public virtual ShipperCompany ShipperCompany { get; set; }
        public virtual FreightType FreightType { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual ICollection<OffersToFreight> OffersToFreights { get; set; }
    }
}
