//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightFinder.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffersToFreight
    {
        public OffersToFreight()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public long OfferId { get; set; }
        public int VehicleId { get; set; }
        public long FreightAdId { get; set; }
        public System.DateTime OfferDate { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual FreightAd FreightAd { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
