//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightFinder.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipperCompany
    {
        public ShipperCompany()
        {
            this.Destinations = new HashSet<Destination>();
            this.FreightAds = new HashSet<FreightAd>();
            this.OffersToVehicles = new HashSet<OffersToVehicle>();
            this.ShipperCompanyUsers = new HashSet<ShipperCompanyUser>();
        }
    
        public int ShipperCompanyId { get; set; }
        public int CompanyId_FK { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Destination> Destinations { get; set; }
        public virtual ICollection<FreightAd> FreightAds { get; set; }
        public virtual ICollection<OffersToVehicle> OffersToVehicles { get; set; }
        public virtual ICollection<ShipperCompanyUser> ShipperCompanyUsers { get; set; }
    }
}
