//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightFinder.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportationCompany
    {
        public TransportationCompany()
        {
            this.CreditTransfers = new HashSet<CreditTransfer>();
            this.Employments = new HashSet<Employment>();
            this.TransportationCompanyUsers = new HashSet<TransportationCompanyUser>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int TransportationCompanyId { get; set; }
        public int CompanyId_FK { get; set; }
        public string KDocumentNumber { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<CreditTransfer> CreditTransfers { get; set; }
        public virtual ICollection<Employment> Employments { get; set; }
        public virtual ICollection<TransportationCompanyUser> TransportationCompanyUsers { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
