//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightFinder.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TransactionId { get; set; }
        public int VehicleId { get; set; }
        public long OfferId { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual OffersToFreight OffersToFreight { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
