//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightFinder.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthorisationType
    {
        public UserAuthorisationType()
        {
            this.ShipperCompanyUsers = new HashSet<ShipperCompanyUser>();
            this.TransportationCompanyUsers = new HashSet<TransportationCompanyUser>();
        }
    
        public int AuthorisationTypeId { get; set; }
        public string AuthorisationTypeName { get; set; }
    
        public virtual ICollection<ShipperCompanyUser> ShipperCompanyUsers { get; set; }
        public virtual ICollection<TransportationCompanyUser> TransportationCompanyUsers { get; set; }
    }
}
