//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightFinder.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Drivers = new HashSet<Driver>();
            this.ShipperCompanyUsers = new HashSet<ShipperCompanyUser>();
            this.TransportationCompanyUsers = new HashSet<TransportationCompanyUser>();
        }
    
        public int UserId { get; set; }
        public long TC { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int UserType_Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string PicturePath { get; set; }
    
        public virtual ICollection<Driver> Drivers { get; set; }
        public virtual ICollection<ShipperCompanyUser> ShipperCompanyUsers { get; set; }
        public virtual ICollection<TransportationCompanyUser> TransportationCompanyUsers { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
