//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightFinder.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleAd
    {
        public VehicleAd()
        {
            this.OffersToVehicles = new HashSet<OffersToVehicle>();
        }
    
        public int VehicleAdId { get; set; }
        public int VehicleId { get; set; }
        public decimal Lon { get; set; }
        public decimal Lat { get; set; }
        public System.DateTime AdDate { get; set; }
        public string DestinationCity { get; set; }
        public string DestinationCounty { get; set; }
        public bool IsTaken { get; set; }
        public bool IsValid { get; set; }
    
        public virtual ICollection<OffersToVehicle> OffersToVehicles { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
